In [25]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

import pandas as pd
from sklearn.datasets import load_digits
import numpy as np

In [4]:
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [17]:
len(digits.data)

1797

# Tune Parameters Manually

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

y_train

array([8, 6, 2, ..., 8, 5, 2])

In [14]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test, y_test)

0.43703703703703706

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),digits.data,digits.target,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [21]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),digits.data,digits.target,cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [22]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),digits.data,digits.target,cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [28]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),digits.data, digits.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores


{'rbf_1': 0.448545341999381,
 'rbf_10': 0.47636645001547506,
 'rbf_20': 0.47636645001547506,
 'linear_1': 0.9476973073351903,
 'linear_10': 0.9476973073351903,
 'linear_20': 0.9476973073351903}

# Using GridSearch

In [54]:

from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(svm.SVC(gamma='auto'),{
    
    'C':[1,10,20],
    'kernel':['rbf','linear']},
     cv=5,return_train_score=False
)

clf.fit(digits.data,digits.target)
clf.cv_results_

{'mean_fit_time': array([0.35278687, 0.03217897, 0.36617894, 0.04070473, 0.36790996,
        0.03124804]),
 'std_fit_time': array([1.85472883e-02, 6.88831241e-03, 2.09383813e-02, 4.28969150e-03,
        1.95059589e-02, 9.46494734e-07]),
 'mean_score_time': array([0.04197211, 0.01121292, 0.04492378, 0.00499501, 0.03944087,
        0.00625029]),
 'std_score_time': array([0.00624065, 0.00553155, 0.00163393, 0.00409473, 0.00702902,
        0.00765501]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [37]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.377552      0.047565         0.043195    6.398439e-03       1   
1       0.033595      0.003199         0.008000    5.060182e-03       1   
2       0.350355      0.019197         0.039995    1.393475e-06      10   
3       0.030396      0.003200         0.008000    5.560829e-07      10   
4       0.339156      0.010851         0.038395    3.199840e-03      20   
5       0.035196      0.006398         0.009598    3.198433e-03      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.411111   
1       linear   {'C': 1, 'kernel': 'linear'}           0.963889   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.452778   
3       linear  {'C': 10, 'kernel': 'linear'}           0.963889   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.452778   
5       linear  {'C': 20, 'kernel': 'linear'}           0.963889   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.450000           0.454039           0.448468           0.479109   
1           0.919444           0.966574           0.963788           0.924791   
2           0.469444           0.479109           0.479109           0.501393   
3           0.919444           0.966574           0.963788           0.924791   
4           0.469444           0.479109           0.479109           0.501393   
5           0.919444           0.966574           0.963788           0.924791   

   mean_test_score  std_test_score  rank_test_score  
0         0.448545        0.021761                6  
1         0.947697        0.020978                1  
2         0.476366        0.015784                4  
3         0.947697        0.020978                1  
4         0.476366        0.015784                4  
5         0.947697        0.020978                1

In [38]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.448545
1       1       linear         0.947697
2      10          rbf         0.476366
3      10       linear         0.947697
4      20          rbf         0.476366
5      20       linear         0.947697

In [40]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [41]:
clf.best_score_

0.9476973073351903

In [42]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

# Using RandomizedSearchCV

In [44]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=4
)
rs.fit(digits.data, digits.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.448545
1       1       linear         0.947697
2      20       linear         0.947697
3      20          rbf         0.476366

In [60]:
model_params={
    
    'svm': {
        'model':svm.SVC(gamma='auto'),
        'params':{
          
            'C':[1,5,10,20],
            'kernel':['rbf','linear']
        }
    },
    
    'random_forest':{
        
        'model':RandomForestClassifier(),
        'params': {
            
            'n_estimators':[1,5,10]
        }
    },
    
    'logistic_regression':{
        
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    },
    
    'decision_tree':{
        
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion' :['gini', 'entropy'],
             'splitter':['best','random'] 
        }
    },
    
    'gaussian_nb':{
        'model':GaussianNB(),
        'params':{}
        
    },
    
    'multinomial_nb':{
        'model':MultinomialNB(),
        'params':{}
    
    }
}

In [61]:
scores=[]

for model_name,mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data,digits.target)
    scores.append({
        'model':model_name,
        'params':clf.best_params_,
        'score':clf.best_score_
    })
    
df=pd.DataFrame(scores, columns=['model','params','score'])
df

model                                        params     score
0                  svm                  {'C': 1, 'kernel': 'linear'}  0.947697
1        random_forest                          {'n_estimators': 10}  0.907640
2  logistic_regression                                      {'C': 1}  0.922114
3        decision_tree  {'criterion': 'entropy', 'splitter': 'best'}  0.809152
4          gaussian_nb                                            {}  0.806928
5       multinomial_nb                                            {}  0.870350

In [ ]:
scores=[]

for model_name,mp in model_params.items():
    gs_cv=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    gs_cv.fit(X_train,y_train)
    scores.append({
        'model':model_name,
        'best_params':gs_cv.best_params_,
        'score':gs_cv.best_score_
    })

    
models=pd.DataFrame(scores, columns=['Model','Params','Score'])
models


model_params={
    
    'svm': {
        'model':svm.SVC(gamma='auto'),
        'params':{
          
            'C':[1,5,10,20],
            'kernel':['rbf','linear']
        }
    },
    
    'random_forest':{
        
        'model':RandomForestClassifier(),
        'params': {
            
            'n_estimators':[1,5,10]
        }
    },
    
    'logistic_regression':{
        
        'model':LogisticRegression(),
        'params':{
            'C':[1,5,10]
        }
    },
    
    'decision_tree':{
        
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion' :['gini', 'entropy'],
             'splitter':['best','random'] 
        }
    }
}